---

- name: Copy dotfiles
  copy:
    src: "../files/{{ item }}"
    dest: "{{ ansible_env.HOME }}/{{ item }}"
  become_user: "{{ ansible_env.USER }}"
  with_items:
    - .gitconfig
    - .gitconfig-github
    - .zshrc
    - .antigenrc
