---
# Rôle: Installation des paquets de base

- name: Ensure that Aptitude repositories are up to date
  apt:
    update_cache: true
    cache_valid_time: "{{ aptcachetime }}"

- name: Install common packages
  apt:
    state: present
    update_cache: true
    cache_valid_time: "{{ aptcachetime }}"
    name:
      - aptitude
      - build-essential
      - curl
      - git
      - gnupg
      - grep
      - gzip
      - htop
      - jq
      - less
      - make
      - software-properties-common
      - tar
      - unrar
      - unzip
      - vim
      - wget
      - whois
      - zip

- name: Upgrade installed packages
  apt:
    upgrade: safe
    update_cache: true
    force_apt_get: true
