---
- name: Installer les prérequis
  apt:
    name: [apt-transport-https, ca-certificates, software-properties-common, curl, gnupg]
    update_cache: true

- name: Créer le dossier keyrings
  file:
    path: /usr/share/keyrings
    state: directory
    mode: '0755'

- name: Télécharger la clé GPG Docker
  shell: |
    curl -fsSL https://download.docker.com/linux/ubuntu/gpg | \
    gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg
  args:
    creates: /usr/share/keyrings/docker-archive-keyring.gpg

- name: Ajouter le dépôt Docker
  apt_repository:
    repo: "deb [arch=amd64 signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/{{ ansible_distribution | lower }} {{ ansible_distribution_release }} stable"
    filename: docker
    state: present

- name: Installer Docker CE
  apt:
    name: [docker-ce, docker-ce-cli, containerd.io, docker-buildx-plugin, docker-compose-plugin]
    update_cache: true

- name: Créer le groupe docker
  group:
    name: docker
    state: present

- name: Ajouter l'utilisateur au groupe docker
  user:
    name: "{{ ansible_env.USER }}"
    groups: docker
    append: true

- name: Activer le service Docker
  systemd:
    name: docker
    enabled: true
    state: started
